### ISSUE TITLE
Ellipses are split off into sentences

### ISSUE THREAD

**Issue by tslater** [neurosnap/sentences#12]
The out put of this selection of text:

> “Can’t, Tom, I’m on Hogwarts business,” said Hagrid, clapping his great hand on Harry’s shoulder and making Harry’s knees buckle.
“Good Lord,” said the bartender, peering at Harry, “is this — can this be — ?”
The Leaky Cauldron had suddenly gone completely still and silent.
“Bless my soul,” whispered the old bartender, “Harry Potter . . . what an honor.”
He hurried out from behind the bar, rushed toward Harry and seized his hand, tears in his eyes.
“Welcome back, Mr. Potter, welcome back.”
> 

is:

```
“Can’t, Tom, I’m on Hogwarts business,” said Hagrid, clapping his great hand on Harry’s shoulder and making Harry’s knees buckle.
“Good Lord,” said the bartender, peering at Harry, “is this — can this be — ?”
The Leaky Cauldron had suddenly gone completely still and silent.
“Bless my soul,” whispered the old bartender, “Harry Potter . . . what an honor.”
He hurried out from behind the bar, rushed toward Harry and seized his hand, tears in his eyes.
“Welcome back, Mr. Potter, welcome back.”
1 characters remaining
“Can’t, Tom, I’m on Hogwarts business,” said Hagrid, clapping his great hand on Harry’s shoulder and making Harry’s knees buckle.
“Good Lord,” said the bartender, peering at Harry, “is this — can this be — ?”
The Leaky Cauldron had suddenly gone completely still and silent.
“Bless my soul,” whispered the old bartender, “Harry Potter .
.
.
what an honor.”
He hurried out from behind the bar, rushed toward Harry and seized his hand, tears in his eyes.
“Welcome back, Mr. Potter, welcome back.”
````

**Comment by neurosnap** [comment]
Thanks for the issue!  I'll look into this issue and get a fix for it!  Thanks!

**Comment by neurosnap** [comment]
Sorry it took so long to get to this issue.  I have a PR to fix this.  I just need to test it a little more before merging it in.
