### ISSUE TITLE
Installation instructionss broken, binary links dead

### ISSUE THREAD

**Issue by ckingdev** [neurosnap/sentences#20]
When trying to download the binaries, I'm getting something like this for all of them.

`<Error>
<Code>AllAccessDisabled</Code>
<Message>All access to this object has been disabled</Message><RequestId>7268EB2B3DC8532F</RequestId>
<HostId>i2U6tSOMH/7Kyq29rzKr/A7HubUHQRQI/01b8nsYxBshadyeuc1jwRBDtHjaGA26ivrIH9tTEHU=</HostId>
</Error>`

Also, the commands in the readme are incorrect- sentences/cmd/sentences no longer exists as cmd was renamed to _cmd.

**Comment by neurosnap** [comment]
Thanks for notifying me!  I have fixed both issues.
