### ISSUE TITLE
Loadtraining fails with 

### ISSUE THREAD

**Issue by the42** [neurosnap/sentences#9]
Instead of compiling the assets with go-bindata I load the json files like 

	f, err := os.Open(initalisationfilenames[lang].segmentationfilename)
	if err != nil {
		return nil, err
	}
	b, err := ioutil.ReadAll(f)
	if err != nil {
		return nil, err
	}

The results seem to be correct, can you confirm?

**Comment by neurosnap** [comment]
Greetings!

Could you please post how you are loading the data into `sentences` as well as display any errors?

Thanks!

**Comment by the42** [comment]
Sorry, you misunderstood, that was only for my confirmation if a code like that:

	f, err := os.Open("data/german.json")
	if err != nil {
		return nil, err
	}
	b, err := ioutil.ReadAll(f)
	if err != nil {
		return nil, err
	}

	training, err := sentences.LoadTraining(b)
	if err != nil {
		return nil, errors.New("LoadTraining failed: " + err.Error())
	}
	r.tokenizer = sentences.NewSentenceTokenizer(training)

is also supposed to work INSTEAD embedding as a binary blob into the executable. That's because I don't know if something more happens when calling `make "lang"` besised go-binifying the json source.

Thank you!

**Comment by neurosnap** [comment]
Yes it should work as long as that json file is always accompanied with the go executable.

The main reason I went with embedding the training data into the executable was so I didn't have to worry about how to correctly import the json file.
